name: CI workflow

on: push

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'yarn'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: '5.0'
        mongodb-username: root
        mongodb-password: '12345'
        mongodb-db: test
        
    - name: Install deps
      run: yarn
    
    - name: Run tests
      run: yarn test
    
    - name: Get Coverage for Badge
    run: |
      apt install jq

      echo "COVERAGE=$(cat coverage/coverage-summary.json | jq '.total.statements.pct')" >> $GITHUB_ENV

      # var REF = 'refs/pull/27/merge.json';
      REF=${{ github.ref }}

      # console.log('github.ref: ' + REF);
      echo "github.ref: $REF"

      # var PATHS = REF.split('/');
      IFS='/' read -ra PATHS <<< "$REF"

      # var BRANCH_NAME = PATHS[1] + PATHS[2];
      BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"

      # console.log(BRANCH_NAME); // 'pull_27'
      echo $BRANCH_NAME

      # process.env.BRANCH = 'pull_27';
      echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV

  - name: Create badge
    uses: schneegans/dynamic-badges-action@v1.0.0
    with:
      auth: ${{ secrets.GIST_SECRET }}
      gistID: 1013be5684953ab9aa1dec8d2d663c6d
      filename: SPIRA-Dashboard__${{ env.BRANCH }}.json
      label: Coverage
      message: ${{ env.COVERAGE }}
      color: green
      namedLogo: jest